/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppBookingsPageIndexImport } from './routes/app/bookings-page/index'
import { Route as AppAdminIndexImport } from './routes/app/admin/index'
import { Route as AppBookingPageIdImport } from './routes/app/booking-page/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppBookingsPageIndexRoute = AppBookingsPageIndexImport.update({
  id: '/bookings-page/',
  path: '/bookings-page/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppAdminIndexRoute = AppAdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppBookingPageIdRoute = AppBookingPageIdImport.update({
  id: '/booking-page/$id',
  path: '/booking-page/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/app/booking-page/$id': {
      id: '/app/booking-page/$id'
      path: '/booking-page/$id'
      fullPath: '/app/booking-page/$id'
      preLoaderRoute: typeof AppBookingPageIdImport
      parentRoute: typeof AppRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/bookings-page/': {
      id: '/app/bookings-page/'
      path: '/bookings-page'
      fullPath: '/app/bookings-page'
      preLoaderRoute: typeof AppBookingsPageIndexImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppBookingPageIdRoute: typeof AppBookingPageIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppBookingsPageIndexRoute: typeof AppBookingsPageIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBookingPageIdRoute: AppBookingPageIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppBookingsPageIndexRoute: AppBookingsPageIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/booking-page/$id': typeof AppBookingPageIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/bookings-page': typeof AppBookingsPageIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/booking-page/$id': typeof AppBookingPageIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/bookings-page': typeof AppBookingsPageIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/booking-page/$id': typeof AppBookingPageIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/bookings-page/': typeof AppBookingsPageIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/booking-page/$id'
    | '/app/admin'
    | '/app/bookings-page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/booking-page/$id'
    | '/app/admin'
    | '/app/bookings-page'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/booking-page/$id'
    | '/app/admin/'
    | '/app/bookings-page/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/booking-page/$id",
        "/app/admin/",
        "/app/bookings-page/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/app/booking-page/$id": {
      "filePath": "app/booking-page/$id.tsx",
      "parent": "/app"
    },
    "/app/admin/": {
      "filePath": "app/admin/index.tsx",
      "parent": "/app"
    },
    "/app/bookings-page/": {
      "filePath": "app/bookings-page/index.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
